In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('train.csv')

In [ ]:
df.head()

id keyword location                                               text  \
0   1     NaN      NaN  Our Deeds are the Reason of this #earthquake M...   
1   4     NaN      NaN             Forest fire near La Ronge Sask. Canada   
2   5     NaN      NaN  All residents asked to 'shelter in place' are ...   
3   6     NaN      NaN  13,000 people receive #wildfires evacuation or...   
4   7     NaN      NaN  Just got sent this photo from Ruby #Alaska as ...   

   target  
0       1  
1       1  
2       1  
3       1  
4       1

In [ ]:
###Drop Nan Values
df=df.dropna()

In [ ]:
## Get the Independent Features

X=df.drop('target',axis=1)

In [ ]:
## Get the Dependent features
y=df['target']

In [ ]:
X.shape

(5080, 4)

In [ ]:
y.shape

(5080,)

In [ ]:
import tensorflow as tf

In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [ ]:
### Vocabulary size
voc_size=5000

In [ ]:
#Onehot Representation

In [ ]:
messages=X.copy()

In [ ]:
messages.reset_index(inplace=True)

In [ ]:
messages['text'][1]

'We always try to bring the heavy. #metal #RT http://t.co/YAo1e0xngw'

In [ ]:
import nltk
import re
from nltk.corpus import stopwords

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
### Dataset Preprocessing
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    print(i)
    review = re.sub('[^a-zA-Z]', ' ',messages['text'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

Streaming output truncated to the last 5000 lines.
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
3

In [ ]:
corpus

['bbcmtd wholesal market ablaz http co lhyxeohi c',
 'alway tri bring heavi metal rt http co yao e xngw',
 'africanbaz break news nigeria flag set ablaz aba http co nndbgwyei',
 'cri set ablaz',
 'plu side look sky last night ablaz http co qqsmshaj n',
 'phdsquar mufc built much hype around new acquisit doubt set epl ablaz season',
 'inec offic abia set ablaz http co imaomknna',
 'ablaz lord',
 'check http co roi nsmejj http co tj zjin http co yduixefip http co lxtjc kl nsfw',
 'awesom time visit cfc head offic ancop site ablaz thank tita vida take care us',
 'west burn thousand wildfir ablaz california alon http co vl tbr wbr',
 'check http co roi nsmejj http co tj zjin http co yduixefip http co lxtjc kl nsfw',
 'first night retain quit weird better get use wear everi singl night next year least',
 'deputi man shot brighton home set ablaz http co gwnrhmso k',
 'man wife get six year jail set ablaz niec http co ev ahoucza',
 'santa cruz head st elizabeth polic superintend lanford salmo

In [ ]:
onehot_repr=[one_hot(words,voc_size)for words in corpus] 
onehot_repr

[[3931, 2329, 4508, 531, 227, 4600, 2609, 2319],
 [3315, 2156, 755, 4881, 607, 4045, 227, 4600, 419, 2947, 2093],
 [1270, 602, 797, 3643, 1593, 417, 531, 2678, 227, 4600, 1573],
 [2366, 417, 531],
 [486, 4556, 3675, 89, 4028, 1242, 531, 227, 4600, 4429, 1364],
 [2551, 2399, 1905, 1778, 4089, 2423, 2950, 645, 1682, 417, 1088, 531, 705],
 [427, 2728, 3202, 417, 531, 227, 4600, 1056],
 [531, 1617],
 [4096,
  227,
  4600,
  3488,
  4473,
  227,
  4600,
  1573,
  121,
  227,
  4600,
  1585,
  227,
  4600,
  589,
  3412,
  2292],
 [3582,
  523,
  1749,
  34,
  498,
  2728,
  3205,
  1426,
  531,
  1692,
  4033,
  4477,
  3312,
  819,
  3621],
 [4982, 3519, 3481, 373, 531, 301, 624, 227, 4600, 1692, 2563, 4016],
 [4096,
  227,
  4600,
  3488,
  4473,
  227,
  4600,
  1573,
  121,
  227,
  4600,
  1585,
  227,
  4600,
  589,
  3412,
  2292],
 [3636,
  1242,
  1943,
  3372,
  1111,
  2891,
  3135,
  1716,
  1501,
  225,
  2217,
  1242,
  2605,
  1487,
  3222],
 [443, 2587, 3027, 2286, 1060, 417

In [ ]:
#Embedding Representation

In [ ]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ... 4600 2609 2319]
 [   0    0    0 ...  419 2947 2093]
 [   0    0    0 ...  227 4600 1573]
 ...
 [   0    0    0 ...  506 2889  314]
 [   0    0    0 ...  227 4600 2532]
 [   0    0    0 ...  227 4600 1358]]


In [ ]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0, 3931, 2329, 4508,  531,  227, 4600, 2609, 2319], dtype=int32)

In [ ]:
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 20, 40)            200000    
                                                                 
 lstm (LSTM)                 (None, 100)               56400     
                                                                 
 dense (Dense)               (None, 1)                 101       
                                                                 
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [ ]:
len(embedded_docs),y.shape

(5080, (5080,))

In [ ]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [ ]:
X_final.shape,y_final.shape

((5080, 20), (5080,))

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

In [ ]:
#Model Training

In [ ]:
### Finally Training
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
54/54 [==============================] - 8s 18ms/step - loss: 0.6515 - accuracy: 0.6098 - val_loss: 0.6216 - val_accuracy: 0.6762
Epoch 2/10
54/54 [==============================] - 0s 7ms/step - loss: 0.4621 - accuracy: 0.7993 - val_loss: 0.5061 - val_accuracy: 0.7662
Epoch 3/10
54/54 [==============================] - 0s 7ms/step - loss: 0.2892 - accuracy: 0.8851 - val_loss: 0.5473 - val_accuracy: 0.7603
Epoch 4/10
54/54 [==============================] - 0s 9ms/step - loss: 0.1940 - accuracy: 0.9327 - val_loss: 0.7247 - val_accuracy: 0.7376
Epoch 5/10
54/54 [==============================] - 0s 7ms/step - loss: 0.1381 - accuracy: 0.9506 - val_loss: 0.8941 - val_accuracy: 0.7394
Epoch 6/10
54/54 [==============================] - 0s 7ms/step - loss: 0.1131 - accuracy: 0.9630 - val_loss: 0.9317 - val_accuracy: 0.7257
Epoch 7/10
54/54 [==============================] - 0s 7ms/step - loss: 0.0862 - accuracy: 0.9715 - val_loss: 1.0366 - val_accuracy: 0.7156
Epoch 8/10
54/54 [=

In [ ]:
#Adding Dropout

In [ ]:
from tensorflow.keras.layers import Dropout
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [ ]:
#Performance Metrics And Accuracy

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
y_pred=model.predict(X_test)
y_pred = y_pred.flatten()
print(y_pred.round(0))

[0. 1. 0. ... 1. 1. 1.]


In [ ]:
# SVM Classification
import pandas as pd
import numpy as np

from sklearn import svm
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report


from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import train_test_split, cross_val_score

In [ ]:
clf = SVC(kernel="linear",gamma=0.0001) #rbf or linear

clf.fit(X_train , y_train)



acc = accuracy_score(y_test, y_pred) * 100

print("Accuracy =", acc)

confusion_matrix(y_test, y_pred)